### ISSUE TITLE
Demo should have navigation

### ISSUE THREAD

**Issue by Kerrick** [secondstreet/ember-material-components-web#13]
[The Demo](https://secondstreet.github.io/ember-material-components-web/) is currently a bunch of components dropped on a single page. Instead, it should be split up with one component or family of components per page, so each can be deep-linked.

**Comment by xtagon** [comment]
Why not use the official Material Components for Web documentation as an example?

**Comment by Kerrick** [comment]
Great idea @xtagon! It looks like they use [this repo](https://github.com/material-components/material-components-site-generator) to generate their docs, so we should be able to effectively utilize that code :+1:

**Comment by KnownSubset** [comment]
#44
