### ISSUE TITLE
menu: breaking change in v0.13

### ISSUE THREAD

**Issue by JackCA** [secondstreet/ember-material-components-web#17]
In the recent [0.13 release](https://github.com/material-components/material-components-web/blob/642fb4364caca59b6de93829b15afe7e535b548a/CHANGELOG.md#breaking-changes):

> menu: Rename symmetric registerDocumentClickHandler/deregisterDocumentClickHandler adapter methods to registerBodyClickHandler/deregisterBodyClickHandler

Because of this, menu's won't close when being click outside of

**Comment by Kerrick** [comment]
The `ember-material-components-web` does not actually install a dependency on `material-components-web` for this very reason. Instead, it depends individually on each `@material/` package, in this case `@material/menu`.

Your app's `package.json` should have `"@material/menu": "0.2.7"` in its `devDependencies`, which does not yet have that breaking change. Can you confirm that your `package.json` does have the correct version of `@material/menu` and does not have `material-components-web`?

**Comment by JackCA** [comment]
Hey @Kerrick, I'm guilty of pushing the dependencies manually on my own in order to take advantage of some of the bugfixes/enhancements that have occurred since the locked-in lower versions.

I should have made it more clear that I did this myself -- sorry! The backwards compatible fix would appear to be to just implement both callbacks with the same function.

Would I be able to try and make that PR using that strategy?

On a related note, what are your upgrade path plans for all of the `@material` namespaced packages?

**Comment by Kerrick** [comment]
You're welcome to make a PR with that strategy, but an even better idea might be to simply upgrade to the newer version of `@material/menu` and only use the new method. PRs are gladly accepted, though! :)

**Comment by Kerrick** [comment]
Regarding your upgrade path question: Ideally, this library will implement every MDC-Web component _and_ stay up-to-date with them all. It's just a matter of devoting development time to that task.
