### ISSUE TITLE
You modified "mdcClassNames" twice 

### ISSUE THREAD

**Issue by marclundgren** [secondstreet/ember-material-components-web#52]
Hello. I've not seen anyone complaining about this symptom. Anytime I click my `mdc-checkbox` component, i see this ember error:

"Assertion Failed: You modified "mdcClassNames" twice on <revv-v3@component:mdc-checkbox::ember842> in a single render. It was rendered in "component:mdc-checkbox" and modified in "component:mdc-checkbox". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details."

```
{{mdc-checkbox
  disabled=false
  ripple=false
  onchange=(action 'toggleSuperAdmin')
  checked=(eq (get changeset 'role') 'super_admin')
}}
```

```js
toggleSuperAdmin() {
  const role = this.get('changeset.role');

  if (role === 'super_admin') {
    this.set('changeset.role', 'admin');
  } else {
    this.set('changeset.role', 'super_admin');
  }
},
```

Am I doing something obviously wrong?

**Comment by marclundgren** [comment]
it looks like this is the root cause:

https://github.com/DockYard/ember-one-way-controls/pull/176

**Comment by marclundgren** [comment]
re-opening. ember-one-way-controls#176 only seems to apply to `select` inputs.

**Comment by marclundgren** [comment]
This doesn't appear to be an issue on the demo

https://secondstreet.github.io/ember-material-components-web/

**Comment by Kerrick** [comment]
@marclundgren Do you have a live Ember Twiddle or other demo (or some code we can check out and run locally) to see the bug in action?

**Comment by marclundgren** [comment]
@Kerrick I made a twiddle, and added `ember-material-components-web` as a dependency, but the ember app is failing with the error `mdc-checkbox` is an unknown helper.

https://ember-twiddle.com/53579d2114868f47c4c62c6f030aa470?openFiles=templates.application.hbs%2C

**Comment by Kerrick** [comment]
I think it didn't happen in the demo site because the demo site is currently on an older version of Ember that doesn't have the assertion.
