### ISSUE TITLE
No Toolbar in Demo

### ISSUE THREAD

**Issue by MrChriZ** [secondstreet/ember-material-components-web#56]
In the demo project here:
https://secondstreet.github.io/ember-material-components-web/

There is no Toolbar component

**Comment by Kerrick** [comment]
Good catch, thanks!

**Comment by KnownSubset** [comment]
There is a [toolbar component](https://secondstreet.github.io/ember-material-components-web/#/?s=Toolbar) in the demo site.  This should be closed.

**Comment by MrChriZ** [comment]
So there is.  Must have been having a wood for the trees day!
Closing!
